name: Continuous Deployment

on:
  push:
    branches:
      - "master"

jobs:
  linux:
    name: ${{ matrix.os }} / ${{ matrix.build_type }} / ${{ matrix.compiler.name }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu-22.04]
        compiler:
          - { name: "GNU-10", compiler: gcc, version: 10 }
        build_type: ["Debug", "Release"]
    env:
      DISPLAY: ":99"
      CONAN_REVISIONS_ENABLED: "1"
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: |
          pip3 install conan
          conan config init
          conan profile update settings.build_type=${{ matrix.build_type }} default
          conan profile update settings.compiler=${{ matrix.compiler.compiler }} default
          conan profile update settings.compiler.version=${{ matrix.compiler.version }} default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan remote add gamedev-center https://eugenekuznetsov.jfrog.io/artifactory/api/conan/gamedev-conan-local --insert 0
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Install package dependencies
        run: |
          sudo sudo apt-get install -y --no-install-recommends libopengl-dev libopengl-dev

      - name: Create package
        run: |
          conan create . --conf tools.system.package_manager:mode=install  --conf tools.system.package_manager:sudo=True

      - name: Deploy
        run: |
          reference=`conan search gamedevkit --raw`
          conan user -p ${{ secrets.CONAN_REMOTE_TOKEN }} -r gamedev-center ${{ secrets.CONAN_REMOTE_USER }}
          conan upload $reference -r gamedev-center --all --confirm --check

  windows:
    name: ${{ matrix.os }} / ${{ matrix.build_type }} / ${{ matrix.compiler.name }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        os: [Windows-2019]
        compiler:
          - { name: "Visual Studio 16", compiler: "Visual Studio", version: 16 }
        build_type: ["Debug", "Release"]
    env:
      CONAN_REVISIONS_ENABLED: "1"
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: |
          pip install conan
          conan --version
          conan profile new default --detect
          conan profile update settings.build_type=${{ matrix.build_type }} default
          conan profile update settings.compiler='${{ matrix.compiler.compiler }}' default
          conan profile update settings.compiler.version=${{ matrix.compiler.version }} default
          conan remote add gamedev-center https://eugenekuznetsov.jfrog.io/artifactory/api/conan/gamedev-conan-local --insert 0

      - name: Create package
        run: |
          conan create .

      - name: Deploy
        run: |
          $reference=(conan search gamedevkit --raw)
          conan user -p ${{ secrets.CONAN_REMOTE_TOKEN }} -r gamedev-center ${{ secrets.CONAN_REMOTE_USER }}
          conan upload $reference -r gamedev-center --all --confirm --check
